### ISSUE TITLE
Add support for layout fields

### ISSUE THREAD

**Issue by besserdesign** [johannschopplich/kirby-content-translator#1]
Thanks for the great plugin! Unfortunately it doesn't work for layout fields with type: layout.
Can you fix that?

**Comment by johannschopplich** [comment]
Yep, support for layout fields is still on the To do list. 🙂

**Comment by besserdesign** [comment]
> Yep, support for layout fields is still on the To do list. 🙂

That's great! Can you already estimate when the feature will be available?

**Comment by johannschopplich** [comment]
I can't estimate the release. It will be faster if you sponsor its development, tho. 😉

**Comment by johannschopplich** [comment]
@besserdesign Should be working with [v0.4.0](https://github.com/johannschopplich/kirby-content-translator/releases/tag/v0.4.0). If an issue occurs, please open a separate issue. Thanks!

**Comment by besserdesign** [comment]
you are great!  Thank you
