### ISSUE TITLE
Option to update slug after translating title

### ISSUE THREAD

**Issue by jonasfeige** [johannschopplich/kirby-content-translator#10]
This would be a great addition. Maybe as on opt-in config option?
I know automatically updating a page's slug isn't always optimal, but I believe many of my clients will not realize that they would need to do this manually after pressing the translate button. I have solved it with a simple `page.changeTitle:after` hook for now.

**Comment by johannschopplich** [comment]
@jonasfeige @grommasdietz This is now possible with the frehsly released [Kirby Content Translator v2](https://kirby.tools/content-translator). It supports a new [`slug` confiuration option](https://kirby.tools/docs/content-translator/configuration#slug) to also update the slug. This works besides title translation, but also standalone.
