### ISSUE TITLE
Translate structure field inside object field

### ISSUE THREAD

**Issue by foxacid** [johannschopplich/kirby-content-translator#15]
While it is possible to translate structure and object fields that are part of a block, it seems that structure fields nested inside object fields can not be translated. 

Even if there was such an option, if it followed the existing pattern for blocks, e.g.:

```yml
myObjectWithStructure:
  - structureInObject
```

it would quickly become unwieldy as mentioned here: https://github.com/johannschopplich/kirby-content-translator/issues/14

Is there a reason for `translatableFields` not simply being inherited by nested fields (whether object, structure or block)?

**Comment by johannschopplich** [comment]
This has been resolved with the [Kirby Content Translator v2](https://kirby.tools/content-translator), which is a complete rewrite and supports proper recursive translation. 🙌
